version: '3.1'

services:
  node-client:
    build: 
      context: ./client
      dockerfile: ./Dockerfile
    container_name: node-client-chat
    restart: unless-stopped
    depends_on:
      - node-server
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - ${CHAT_CLIENT_PORT:-5173}:${CHAT_CLIENT_PORT:-5173}
    command: npm run dev ${CHAT_CLIENT_PORT:-5173}
    networks:
      - chat-network

  node-server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: node-server-chat
    restart: unless-stopped
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${CHAT_SERVER_PORT:-3001}:${CHAT_SERVER_PORT:-3001}
    command: node server.js
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge